# Generated by Django 4.2.8 on 2024-03-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_assignmentsubmission_assignment_tutor_class_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
